# KillKrill Prometheus Configuration
# Monitoring configuration for centralized observability platform

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'killkrill'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"
  - "rules/*.yml"

# Scrape configuration
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # KillKrill Manager
  - job_name: 'killkrill-manager'
    static_configs:
      - targets: ['manager:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # KillKrill Log Receiver
  - job_name: 'killkrill-receiver'
    static_configs:
      - targets: ['receiver:8081']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # KillKrill Metrics Receiver
  - job_name: 'killkrill-metrics'
    static_configs:
      - targets: ['metrics:8082']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # KillKrill Processor (if it exposes metrics)
  - job_name: 'killkrill-processor'
    static_configs:
      - targets: ['processor:8083']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL monitoring (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Elasticsearch monitoring
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 30s
    metrics_path: /_prometheus/metrics

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node exporter for system metrics (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Remote write configuration (for enterprise features)
remote_write:
  - url: "http://prometheus:9090/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
    wal-compression: true