# KillKrill Elasticsearch Configuration - Development
# Minimal configuration for Elasticsearch 8.11

# ======================== Elasticsearch Configuration =========================

# Cluster settings
cluster.name: killkrill-dev
node.name: killkrill-es-dev
node.roles: [master, data, ingest, transform]

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings (single node)
discovery.type: single-node

# Security (disabled for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.ml.enabled: false

# ======================== Performance Tuning =========================

# Memory settings (disabled for containerized development)
bootstrap.memory_lock: false

# Index settings for high throughput
indices.memory.index_buffer_size: 30%
indices.memory.min_index_buffer_size: 96mb

# Query performance
indices.queries.cache.size: 10%
indices.queries.cache.count: 10000

# Request cache for aggregations
indices.requests.cache.size: 2%

# Field data cache (use sparingly)
indices.fielddata.cache.size: 20%

# ======================== Thread Pools =========================

# Search thread pool (optimized for development)
thread_pool.search.size: 2
thread_pool.search.queue_size: 500

# Write thread pool (limited by system)
thread_pool.write.size: 2
thread_pool.write.queue_size: 200

# Get thread pool
thread_pool.get.size: 2
thread_pool.get.queue_size: 100

# ======================== Cluster Settings =========================

cluster.max_shards_per_node: 10000

# Routing allocation
cluster.routing.allocation.enable: all
cluster.routing.allocation.node_concurrent_recoveries: 2
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%

# ======================== Index Templates =========================

# Auto-create index pattern for KillKrill logs
action.auto_create_index: "killkrill-*,elastalert_status*,elastalert_silence*"

# ======================== HTTP Settings =========================

# HTTP compression
http.compression: true
http.compression_level: 3
http.max_content_length: 500mb
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: "OPTIONS, HEAD, GET, POST, PUT, DELETE"
http.cors.allow-headers: "X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization"

# ======================== Logging =========================

# Reduce noise in logs
logger.org.elasticsearch.deprecation: ERROR
logger.org.elasticsearch.transport: WARN
logger.org.elasticsearch.discovery: WARN

# ======================== Recovery Settings =========================

# Index recovery
indices.recovery.max_bytes_per_sec: 100mb

# ======================== Circuit Breaker =========================

# Circuit breaker settings to prevent OOM
indices.breaker.total.use_real_memory: true
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 40%

# ======================== Search Settings =========================

# Search settings
search.max_buckets: 65536
search.default_search_timeout: 60s