---
- name: YOUR PROJECT NAME
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  tasks:
    - name: Run and configure
      tags:
        - run
      include_tasks:
        file: jobs/build/run.yml

    - name: Build
      tags:
        - build
      include_tasks:
        file: jobs/run/build.yml

    - name: Run tests to make sure app is running as expected
      tags:
        - test
      include_tasks:
        file: jobs/tests/test.yml
